def nodes_mapping(cls):
    # def for indexed types
    default_simple_text = {"type": "text"}
    default_half_float = {"type": "half_float"}

    default_keyword = {"type": "keyword", "normalizer": "keyword_lowercase_normalizer"}
    default_curie_keyword = {
        **default_simple_text,
        "analyzer": "curie_tokenizer",
        "fields": {
            "keyword": {"type": "keyword"}
        }
    }

    # def for not indexed types
    index_disabled_text = {
        **default_simple_text,
        "index": False
    }
    index_disabled_bool = {"type": "boolean", "index": False}
    index_disabled_float = {"type": "float", "index": False}
    index_disabled_object = {"type": "object", "enable": False}
    index_disabled_date = {"type": "date", "index": False}


    nodes_props = {
        # generated by DAWG
        "category": default_keyword,
        "description": index_disabled_text,
        "equivalent_identifiers": default_curie_keyword,
        "id": default_curie_keyword,
        "information_content": default_half_float,
        "inheritance": index_disabled_text,
        "in_taxon": default_keyword,
        "name": index_disabled_text,
        "provided_by": index_disabled_text
    }

    return nodes_props


def merged_edges_mapping(cls):
    # def for indexed types
    default_simple_text = {"type": "text"}
    default_half_float = {"type": "half_float"}
    default_keyword = {"type": "keyword", "normalizer": "keyword_lowercase_normalizer"}
    default_curie_keyword = {
        **default_simple_text,
        "analyzer": "curie_tokenizer",
        "fields": {
            "keyword": {"type": "keyword"}
        }
    }

    # def for not indexed types
    index_disabled_text = {
        **default_simple_text,
        "index": False
    }
    index_disabled_bool = {"type": "boolean", "index": False}
    index_disabled_float = {"type": "float", "index": False}
    index_disabled_object = {"type": "object", "enable": False}
    index_disabled_date = {"type": "date", "index": False}

    edges_props = {
        "agent_type": default_keyword,
        "allelic_requirement": index_disabled_text,
        "category": index_disabled_text,

        "has_confidence_score": index_disabled_bool,
        "has_count": index_disabled_bool,
        "has_evidence": index_disabled_bool,
        "has_percentage": index_disabled_bool,
        "has_quotient": index_disabled_bool,
        "has_total": index_disabled_bool,

        "id": index_disabled_text,
        "knowledge_level": default_keyword,
        "negated": index_disabled_bool,

        # will be overridden when merged with nodes
        "object": default_keyword,

        "original_object": index_disabled_text,
        "original_predicate": index_disabled_text,
        "original_subject": index_disabled_text,

        "predicate": default_keyword,

        # generated by us (for now), eq. to old all_predicates
        "predicate_ancestors": default_keyword,
        "publications": index_disabled_text,
        "source_inforeses": default_keyword,
        "sources": index_disabled_object,

        # will be overridden when merged with nodes
        "subject": default_keyword,

        # maybe date type
        "update_date": index_disabled_date,
        "z_score": index_disabled_float,
        "qualifiers": default_keyword
    }

    nodes_props = {
        # generated by DAWG
        "category": default_keyword,
        "description": index_disabled_text,
        "equivalent_identifiers": default_curie_keyword,
        "id": default_curie_keyword,
        "information_content": default_half_float,
        "inheritance": index_disabled_text,
        "in_taxon": default_keyword,
        "name": index_disabled_text,
        "provided_by": index_disabled_text
    }

    return {
            **edges_props,
            "subject": {
                "type": "object",
                "properties": nodes_props
            },
            "object": {
                "type": "object",
                "properties": nodes_props
            },
    }


