def nodes_mapping(cls):
    # def for indexed types
    default_simple_text = {"type": "text"}
    lowercase_text = {
        "type": "text",
        "normalizer": "keyword_lowercase_normalizer"
    }

    default_half_float = {"type": "half_float"}

    default_keyword = {"type": "keyword", "normalizer": "keyword_lowercase_normalizer"}
    default_curie_keyword = {
        **lowercase_text,
        "analyzer": "curie_analyzer",
        "fields": {
            "keyword": {"type": "keyword"}
        }
    }

    # def for not indexed types
    index_disabled_text = {
        **default_simple_text,
        "index": False
    }

    nodes_props = {

        "name": index_disabled_text,

        # generated by DAWG
        "category": default_keyword,

        "id": default_curie_keyword,

        ## fields below are attributes
        "information_content": default_half_float,
        "description": default_simple_text,
        "equivalent_identifiers": default_curie_keyword,

        # always starts with NCBITaxon:
        "in_taxon": default_curie_keyword,

        # no record with these fields
        "provided_by": index_disabled_text,
        "inheritance": index_disabled_text,
    }

    return nodes_props


def merged_edges_mapping(cls):
    # def for indexed types
    default_simple_text = {"type": "text"}
    lowercase_text = {
        "type": "text",
        "normalizer": "keyword_lowercase_normalizer"
    }

    default_half_float = {"type": "half_float"}
    default_keyword = {"type": "keyword", "normalizer": "keyword_lowercase_normalizer"}
    default_curie_keyword = {
        **lowercase_text,
        "analyzer": "curie_analyzer",
        "fields": {
            "keyword": {"type": "keyword"}
        }
    }

    default_integer = {"type": "integer"}

    # def for not indexed types
    index_disabled_text = {
        **default_simple_text,
        "index": False
    }
    index_disabled_bool = {"type": "boolean", "index": False}
    index_disabled_float = {"type": "float", "index": False}
    index_disabled_object = {"type": "object", "enabled": False}
    index_disabled_date = {"type": "date", "index": False}
    default_date = {"type": "date"}

    edges_props = {


        "category": index_disabled_text,
        "id": index_disabled_text,
        "negated": index_disabled_bool,

        # will be overridden when merged with nodes
        "object": default_keyword,

        "predicate": default_keyword,

        # generated by us (for now), eq. to old all_predicates
        "predicate_ancestors": default_keyword,

        "source_inforeses": default_curie_keyword,
        "sources": index_disabled_object,

        # will be overridden when merged with nodes
        "subject": default_keyword,


        # exploded qualifiers
        "subject_form_or_variant_qualifier": default_keyword,
        "qualified_predicate": default_keyword,
        "disease_context_qualifier": default_keyword,
        "frequency_qualifier": default_keyword,
        "onset_qualifier": default_keyword,
        "sex_qualifier": default_keyword,



        ## fields below are attributes
        "knowledge_level": default_keyword,
        "agent_type": default_keyword,

        # the following attributes are indexed since Nov 19 2025
        "original_object": default_curie_keyword,
        "original_predicate": default_curie_keyword,
        "original_subject": default_curie_keyword,
        "publications": default_curie_keyword,

        # always starts with HP:
        "allelic_requirement": default_curie_keyword,

        "update_date": default_date,
        "z_score": default_half_float,
        "has_confidence_score": default_half_float,
        "has_count": default_integer,

        # always starts with ECO:
        "has_evidence": default_curie_keyword,

        "has_percentage": default_half_float,
        "has_quotient": default_half_float,
        "has_total": default_integer,

        # internal control id, for sorting in ES
        "seq_": default_integer
    }

    nodes_props = {

        "name": index_disabled_text,

        # generated by DAWG
        "category": default_keyword,

        "id": default_curie_keyword,

        ## fields below are attributes
        "information_content": default_half_float,
        "description": default_simple_text,
        "equivalent_identifiers": default_curie_keyword,

        # always starts with NCBITaxon:
        "in_taxon": default_curie_keyword,

        # no record with these fields
        "provided_by": index_disabled_text,
        "inheritance": index_disabled_text,

    }

    return {
            **edges_props,
            "subject": {
                "type": "object",
                "properties": nodes_props
            },
            "object": {
                "type": "object",
                "properties": nodes_props
            },
    }


